name: mkdocs-build
on:
  push:
    branches:
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - run: pip install --disable-pip-version-check --upgrade -r requirements.txt
    - run: mkdocs gh-deploy --force
